version: '3.5'

services:
    apache_php:
        build: .docker/apache_php
        container_name: apache_php
        ports:
            - 80:80
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/var/www/html

    db:
        image: mariadb/server:10.4
        container_name: mariadb
        environment:
            MARIADB_DATABASE: mercure
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: db
            MARIADB_PASSWORD: db
        ports:
            - 3306:3306
        volumes:
            - .docker/data/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 3002:80
        depends_on:
            - db

    mercure:
        image: dunglas/mercure
        container_name: mercure
        environment:
            ALLOW_ANONYMOUS: 1
            JWT_KEY: aVerySecretKey
            PUBLISH_ALLOWED_ORIGINS: '*'
            CORS_ALLOWED_ORIGINS: http://localhost
        ports:
            - 3000:80
