version: '2'

services:
    php:
        image: registry-gitlab.eolas.fr/docker/php/7.2:fpm-smart
        container_name: $PHP_CONTAINER_NAME
        volumes:
            - ..:$PHP_ROOT_DIR
        ports:
            - 8008:8008

    apache:
        image: registry-gitlab.eolas.fr/docker/apache:2.4-base
        container_name: $APACHE_CONTAINER_NAME
        environment:
            VHOST_BASE_DOC_ROOT: $PHP_ROOT_DIR
            VHOST_SERVER_NAME: $APACHE_SERVER_NAME
            VHOST_PHP_HOST: $PHP_CONTAINER_NAME
        ports:
            - 80:80
        volumes:
            - ./config/vhosts:/etc/apache2/sites-enabled
            - ..:$PHP_ROOT_DIR
        depends_on:
            - php

    maildev:
        image: registry-gitlab.eolas.fr/docker/maildev:base
        container_name: $MAILDEV_CONTAINER_NAME
        ports:
            - 8001:80

    db:
        image: registry-gitlab.eolas.fr/docker/mysql:10-base
        container_name: $DB_CONTAINER_NAME
        environment:
            MYSQL_DATABASE: $DB_NAME
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD
        volumes:
            - ./data/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: $DB_ADMIN_CONTAINER_NAME
        environment:
            PMA_HOST: $DB_CONTAINER_NAME
            PMA_PORT: $DB_PORT
            PMA_USER: root
            PMA_PASSWORD: $DB_ROOT_PASSWORD
        ports:
            - 8080:80
        depends_on:
            - db

    mercure:
        image: dunglas/mercure
        container_name: $MERCURE_CONTAINER_NAME
        environment:
            JWT_KEY: aVerySecretKey
            ALLOW_ANONYMOUS: 1
            PUBLISH_ALLOWED_ORIGINS: '*'
            CORS_ALLOWED_ORIGINS: http://chloe-briquet.docker.eolas.lan
        ports:
            - 8003:80

    dockerize:
        image: jwilder/dockerize
